In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import json
import requests
import csv
from io import StringIO
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
from math import ceil
import datetime
import calendar

In [2]:
CONNECTION_STRING_AZURE_STORAGE = 'DefaultEndpointsProtocol=https;AccountName=stcis4400spr24;AccountKey=rYko2OP7g7sVhOZyRDr7y+JAdH3ssWiHuFU3So58w0ub02d1REAvapF3LbW4jZKdfBJhgTEEa4wg+AStBaZT1w==;EndpointSuffix=core.windows.net'
CONTAINER_AZURE = 'generalpaymentdata'

# Initialize the BlobServiceClient
blob_service_client = BlobServiceClient.from_connection_string (CONNECTION_STRING_AZURE_STORAGE)
# Get the container client
container_client = blob_service_client.get_container_client (CONTAINER_AZURE)

df_generalpaymentdata = pd.DataFrame()

# List all blobs in the speciffed container
blob_list = container_client.list_blobs ()
for blob in blob_list:
  print (blob.name)
  blob_client = container_client.get_blob_client (blob=blob.name)
  blob_data = blob_client.download_blob()
  blob_content = blob_data.readall().decode('utf-8')
  df = pd.read_csv(StringIO(blob_content))
  # Display the head of the DataFrame
  print (df.shape)
  # sind I have only one csv, I am doing to do the following instructions
  df_generalpaymentdata = df.copy()

/Users/nicolerodriguez/cis4400 group project/Cis4400-project/docs/OP_DTL_GNRL_PGYR2022_P01182024.csv

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9580\4099191409.py:18: DtypeWarning: Columns (4,8,10,12,15,17,18,20,21,22,23,24,26,32,33,34,35,39,46,47,48,51,52,53,54,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(StringIO(blob_content))

(13151823, 91)

In [38]:
df_generalpaymentdata = df.copy()

In [39]:
df_generalpaymentdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151823 entries, 0 to 13151822
Data columns (total 91 columns):
 #   Column                                                             Dtype
---  ------                                                             -----
 0   Change_Type                                                        object
 1   Covered_Recipient_Type                                             object
 2   Teaching_Hospital_CCN                                              float64
 3   Teaching_Hospital_ID                                               float64
 4   Teaching_Hospital_Name                                             object
 5   Covered_Recipient_Profile_ID                                       float64
 6   Covered_Recipient_NPI                                              float64
 7   Covered_Recipient_First_Name                                       object
 8   Covered_Recipient_Middle_Name                                      object
 9   Covered_Recipient_Last_Name                                        object
 10  Covered_Recipient_Name_Suffix                                      object
 11  Recipient_Primary_Business_Street_Address_Line1                    object
 12  Recipient_Primary_Business_Street_Address_Line2                    object
 13  Recipient_City                                                     object
 14  Recipient_State                                                    object
 15  Recipient_Zip_Code                                                 object
 16  Recipient_Country                                                  object
 17  Recipient_Province                                                 object
 18  Recipient_Postal_Code                                              object
 19  Covered_Recipient_Primary_Type_1                                   object
 20  Covered_Recipient_Primary_Type_2                                   object
 21  Covered_Recipient_Primary_Type_3                                   object
 22  Covered_Recipient_Primary_Type_4                                   object
 23  Covered_Recipient_Primary_Type_5                                   object
 24  Covered_Recipient_Primary_Type_6                                   object
 25  Covered_Recipient_Specialty_1                                      object
 26  Covered_Recipient_Specialty_2                                      object
 27  Covered_Recipient_Specialty_3                                      float64
 28  Covered_Recipient_Specialty_4                                      float64
 29  Covered_Recipient_Specialty_5                                      float64
 30  Covered_Recipient_Specialty_6                                      float64
 31  Covered_Recipient_License_State_code1                              object
 32  Covered_Recipient_License_State_code2                              object
 33  Covered_Recipient_License_State_code3                              object
 34  Covered_Recipient_License_State_code4                              object
 35  Covered_Recipient_License_State_code5                              object
 36  Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name          object
 37  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID        int64
 38  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name      object
 39  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State     object
 40  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country   object
 41  Total_Amount_of_Payment_USDollars                                  float64
 42  Date_of_Payment                                                    object
 43  Number_of_Payments_Included_in_Total_Amount                        int64
 44  Form_of_Payment_or_Transfer_of_Value                               object
 45  Nature_of_Payment_or_Transfer_of_Value                             object
 46  City_of_Travel                                                     object
 47  State_of_Travel                                                    object
 48  Country_of_Travel                                                  object
 49  Physician_Ownership_Indicator                                      object
 50  Third_Party_Payment_Recipient_Indicator                            object
 51  Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value  object
 52  Charity_Indicator                                                  object
 53  Third_Party_Equals_Covered_Recipient_Indicator                     object
 54  Contextual_Information                                             object
 55  Delay_in_Publication_Indicator                                     object
 56  Record_ID                                                          int64
 57  Dispute_Status_for_Publication                                     object
 58  Related_Product_Indicator                                          object
 59  Covered_or_Noncovered_Indicator_1                                  object
 60  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1          object
 61  Product_Category_or_Therapeutic_Area_1                             object
 62  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1           object
 63  Associated_Drug_or_Biological_NDC_1                                object
 64  Associated_Device_or_Medical_Supply_PDI_1                          object
 65  Covered_or_Noncovered_Indicator_2                                  object
 66  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2          object
 67  Product_Category_or_Therapeutic_Area_2                             object
 68  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2           object
 69  Associated_Drug_or_Biological_NDC_2                                object
 70  Associated_Device_or_Medical_Supply_PDI_2                          object
 71  Covered_or_Noncovered_Indicator_3                                  object
 72  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3          object
 73  Product_Category_or_Therapeutic_Area_3                             object
 74  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3           object
 75  Associated_Drug_or_Biological_NDC_3                                object
 76  Associated_Device_or_Medical_Supply_PDI_3                          object
 77  Covered_or_Noncovered_Indicator_4                                  object
 78  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4          object
 79  Product_Category_or_Therapeutic_Area_4                             object
 80  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4           object
 81  Associated_Drug_or_Biological_NDC_4                                object
 82  Associated_Device_or_Medical_Supply_PDI_4                          object
 83  Covered_or_Noncovered_Indicator_5                                  object
 84  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5          object
 85  Product_Category_or_Therapeutic_Area_5                             object
 86  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5           object
 87  Associated_Drug_or_Biological_NDC_5                                object
 88  Associated_Device_or_Medical_Supply_PDI_5                          object
 89  Program_Year                                                       int64
 90  Payment_Publication_Date                                           object
dtypes: float64(9), int64(4), object(78)
memory usage: 8.9+ GB

In [40]:
df_generalpaymentdata.head()

,Change_Type,Covered_Recipient_Type,Teaching_Hospital_CCN,Teaching_Hospital_ID,Teaching_Hospital_Name,Covered_Recipient_Profile_ID,Covered_Recipient_NPI,Covered_Recipient_First_Name,Covered_Recipient_Middle_Name,Covered_Recipient_Last_Name,...,Associated_Drug_or_Biological_NDC_4,Associated_Device_or_Medical_Supply_PDI_4,Covered_or_Noncovered_Indicator_5,Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5,Product_Category_or_Therapeutic_Area_5,Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5,Associated_Drug_or_Biological_NDC_5,Associated_Device_or_Medical_Supply_PDI_5,Program_Year,Payment_Publication_Date
0,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1357816.0,1.154649e+09,JUSTIN,NaN,MITCHELL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,01/18/2024
1,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1358188.0,1.588059e+09,RAVI,NaN,PATEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,01/18/2024
2,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,1358188.0,1.588059e+09,RAVI,NaN,PATEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,01/18/2024
3,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,4218571.0,1.609230e+09,JACOB,NaN,PFEIFFER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,01/18/2024
4,UNCHANGED,Covered Recipient Physician,NaN,NaN,NaN,5705160.0,1.740774e+09,JEREMY,MICHAEL,PHILIPSEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,01/18/2024

In [41]:
#drop the empty rows and columns
df_generalpaymentdata = df_generalpaymentdata.dropna(axis=1, how='all')
df_generalpaymentdata = df_generalpaymentdata.dropna(axis=0, how='all')
df_generalpaymentdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151823 entries, 0 to 13151822
Data columns (total 87 columns):
 #   Column                                                             Dtype
---  ------                                                             -----
 0   Change_Type                                                        object
 1   Covered_Recipient_Type                                             object
 2   Teaching_Hospital_CCN                                              float64
 3   Teaching_Hospital_ID                                               float64
 4   Teaching_Hospital_Name                                             object
 5   Covered_Recipient_Profile_ID                                       float64
 6   Covered_Recipient_NPI                                              float64
 7   Covered_Recipient_First_Name                                       object
 8   Covered_Recipient_Middle_Name                                      object
 9   Covered_Recipient_Last_Name                                        object
 10  Covered_Recipient_Name_Suffix                                      object
 11  Recipient_Primary_Business_Street_Address_Line1                    object
 12  Recipient_Primary_Business_Street_Address_Line2                    object
 13  Recipient_City                                                     object
 14  Recipient_State                                                    object
 15  Recipient_Zip_Code                                                 object
 16  Recipient_Country                                                  object
 17  Recipient_Province                                                 object
 18  Recipient_Postal_Code                                              object
 19  Covered_Recipient_Primary_Type_1                                   object
 20  Covered_Recipient_Primary_Type_2                                   object
 21  Covered_Recipient_Primary_Type_3                                   object
 22  Covered_Recipient_Primary_Type_4                                   object
 23  Covered_Recipient_Primary_Type_5                                   object
 24  Covered_Recipient_Primary_Type_6                                   object
 25  Covered_Recipient_Specialty_1                                      object
 26  Covered_Recipient_Specialty_2                                      object
 27  Covered_Recipient_License_State_code1                              object
 28  Covered_Recipient_License_State_code2                              object
 29  Covered_Recipient_License_State_code3                              object
 30  Covered_Recipient_License_State_code4                              object
 31  Covered_Recipient_License_State_code5                              object
 32  Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name          object
 33  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID        int64
 34  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name      object
 35  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State     object
 36  Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country   object
 37  Total_Amount_of_Payment_USDollars                                  float64
 38  Date_of_Payment                                                    object
 39  Number_of_Payments_Included_in_Total_Amount                        int64
 40  Form_of_Payment_or_Transfer_of_Value                               object
 41  Nature_of_Payment_or_Transfer_of_Value                             object
 42  City_of_Travel                                                     object
 43  State_of_Travel                                                    object
 44  Country_of_Travel                                                  object
 45  Physician_Ownership_Indicator                                      object
 46  Third_Party_Payment_Recipient_Indicator                            object
 47  Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value  object
 48  Charity_Indicator                                                  object
 49  Third_Party_Equals_Covered_Recipient_Indicator                     object
 50  Contextual_Information                                             object
 51  Delay_in_Publication_Indicator                                     object
 52  Record_ID                                                          int64
 53  Dispute_Status_for_Publication                                     object
 54  Related_Product_Indicator                                          object
 55  Covered_or_Noncovered_Indicator_1                                  object
 56  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1          object
 57  Product_Category_or_Therapeutic_Area_1                             object
 58  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1           object
 59  Associated_Drug_or_Biological_NDC_1                                object
 60  Associated_Device_or_Medical_Supply_PDI_1                          object
 61  Covered_or_Noncovered_Indicator_2                                  object
 62  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2          object
 63  Product_Category_or_Therapeutic_Area_2                             object
 64  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2           object
 65  Associated_Drug_or_Biological_NDC_2                                object
 66  Associated_Device_or_Medical_Supply_PDI_2                          object
 67  Covered_or_Noncovered_Indicator_3                                  object
 68  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3          object
 69  Product_Category_or_Therapeutic_Area_3                             object
 70  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3           object
 71  Associated_Drug_or_Biological_NDC_3                                object
 72  Associated_Device_or_Medical_Supply_PDI_3                          object
 73  Covered_or_Noncovered_Indicator_4                                  object
 74  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4          object
 75  Product_Category_or_Therapeutic_Area_4                             object
 76  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4           object
 77  Associated_Drug_or_Biological_NDC_4                                object
 78  Associated_Device_or_Medical_Supply_PDI_4                          object
 79  Covered_or_Noncovered_Indicator_5                                  object
 80  Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5          object
 81  Product_Category_or_Therapeutic_Area_5                             object
 82  Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5           object
 83  Associated_Drug_or_Biological_NDC_5                                object
 84  Associated_Device_or_Medical_Supply_PDI_5                          object
 85  Program_Year                                                       int64
 86  Payment_Publication_Date                                           object
dtypes: float64(5), int64(4), object(78)
memory usage: 8.5+ GB

In [42]:
#only keep the id needed
df_generalpaymentdata = df_generalpaymentdata[['Total_Amount_of_Payment_USDollars','Date_of_Payment',
                                              'Number_of_Payments_Included_in_Total_Amount',
                                              'Form_of_Payment_or_Transfer_of_Value',
                                              'Physician_Ownership_Indicator',
                                              'Program_Year',
                                              'Payment_Publication_Date',
                                              'Covered_Recipient_First_Name',
                                              'Covered_Recipient_Middle_Name',
                                              'Covered_Recipient_Last_Name',
                                              'Covered_Recipient_Primary_Type_1',
                                              'Covered_Recipient_Specialty_1',
                                              'Covered_Recipient_License_State_code1',
                                              'Nature_of_Payment_or_Transfer_of_Value',
                                              'Teaching_Hospital_ID',
                                              'Teaching_Hospital_Name',
                                              'Recipient_Primary_Business_Street_Address_Line1',
                                              'Recipient_City',
                                              'Recipient_State',
                                              'Recipient_Zip_Code']]
df_generalpaymentdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151823 entries, 0 to 13151822
Data columns (total 20 columns):
 #   Column                                           Dtype
---  ------                                           -----
 0   Total_Amount_of_Payment_USDollars                float64
 1   Date_of_Payment                                  object
 2   Number_of_Payments_Included_in_Total_Amount      int64
 3   Form_of_Payment_or_Transfer_of_Value             object
 4   Physician_Ownership_Indicator                    object
 5   Program_Year                                     int64
 6   Payment_Publication_Date                         object
 7   Covered_Recipient_First_Name                     object
 8   Covered_Recipient_Middle_Name                    object
 9   Covered_Recipient_Last_Name                      object
 10  Covered_Recipient_Primary_Type_1                 object
 11  Covered_Recipient_Specialty_1                    object
 12  Covered_Recipient_License_State_code1            object
 13  Nature_of_Payment_or_Transfer_of_Value           object
 14  Teaching_Hospital_ID                             float64
 15  Teaching_Hospital_Name                           object
 16  Recipient_Primary_Business_Street_Address_Line1  object
 17  Recipient_City                                   object
 18  Recipient_State                                  object
 19  Recipient_Zip_Code                               object
dtypes: float64(2), int64(2), object(16)
memory usage: 2.0+ GB

In [44]:
#assign the data type
df_generalpaymentdata['Date_of_Payment'] = pd.to_datetime(df_generalpaymentdata['Date_of_Payment'])
df_generalpaymentdata['Payment_Publication_Date'] = pd.to_datetime(df_generalpaymentdata['Payment_Publication_Date'])

data_types = {
    'Total_Amount_of_Payment_USDollars': 'float',
    'Number_of_Payments_Included_in_Total_Amount': 'int',
    'Program_Year': 'int',
    'Teaching_Hospital_ID': 'string',
}

# Convert all 'object' type columns to 'string' type
for column, dtype in df_generalpaymentdata.dtypes.items():
    if dtype == 'object':
        data_types[column] = 'string'

# Apply the transformations
df_generalpaymentdata = df_generalpaymentdata.astype(data_types)

df_generalpaymentdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151823 entries, 0 to 13151822
Data columns (total 20 columns):
 #   Column                                           Dtype
---  ------                                           -----
 0   Total_Amount_of_Payment_USDollars                float64
 1   Date_of_Payment                                  datetime64[ns]
 2   Number_of_Payments_Included_in_Total_Amount      int32
 3   Form_of_Payment_or_Transfer_of_Value             string
 4   Physician_Ownership_Indicator                    string
 5   Program_Year                                     int32
 6   Payment_Publication_Date                         datetime64[ns]
 7   Covered_Recipient_First_Name                     string
 8   Covered_Recipient_Middle_Name                    string
 9   Covered_Recipient_Last_Name                      string
 10  Covered_Recipient_Primary_Type_1                 string
 11  Covered_Recipient_Specialty_1                    string
 12  Covered_Recipient_License_State_code1            string
 13  Nature_of_Payment_or_Transfer_of_Value           string
 14  Teaching_Hospital_ID                             string
 15  Teaching_Hospital_Name                           string
 16  Recipient_Primary_Business_Street_Address_Line1  string
 17  Recipient_City                                   string
 18  Recipient_State                                  string
 19  Recipient_Zip_Code                               string
dtypes: datetime64[ns](2), float64(1), int32(2), string(15)
memory usage: 1.9 GB

In [47]:
# Creating Dimension Tables
# Dim Covered Recipient
dim_covered_recipient = df_generalpaymentdata[['Covered_Recipient_First_Name', 'Covered_Recipient_Middle_Name',
                            'Covered_Recipient_Last_Name', 'Covered_Recipient_Primary_Type_1',
                            'Covered_Recipient_Specialty_1', 'Covered_Recipient_License_State_code1']].drop_duplicates().reset_index(drop=True)
dim_covered_recipient['dim_Covered_Recipient_ID'] = range(1, len(dim_covered_recipient) + 1)

# Dim Teaching Hospital
dim_teaching_hospital = df_generalpaymentdata[['Teaching_Hospital_ID', 'Teaching_Hospital_Name',
                            'Recipient_Primary_Business_Street_Address_Line1', 'Recipient_City',
                            'Recipient_State', 'Recipient_Zip_Code']].drop_duplicates().reset_index(drop=True)
dim_teaching_hospital['dim_Teaching_Hospital_ID'] = range(1, len(dim_teaching_hospital) + 1)

# Dim Payment Detail
dim_payment_detail = df_generalpaymentdata[['Date_of_Payment', 'Program_Year', 'Payment_Publication_Date', 
                         'Form_of_Payment_or_Transfer_of_Value', 'Nature_of_Payment_or_Transfer_of_Value']].drop_duplicates().reset_index(drop=True)
dim_payment_detail['dim_Payment_Detail_ID'] = range(1, len(dim_payment_detail) + 1)

# Creating mappings
covered_recipient_mapping = dim_covered_recipient.set_index(['Covered_Recipient_First_Name', 'Covered_Recipient_Middle_Name',
                                                             'Covered_Recipient_Last_Name', 'Covered_Recipient_Primary_Type_1',
                                                             'Covered_Recipient_Specialty_1', 'Covered_Recipient_License_State_code1'])['dim_Covered_Recipient_ID']

teaching_hospital_mapping = dim_teaching_hospital.set_index(['Teaching_Hospital_ID', 'Teaching_Hospital_Name',
                                                             'Recipient_Primary_Business_Street_Address_Line1', 'Recipient_City',
                                                             'Recipient_State', 'Recipient_Zip_Code'])['dim_Teaching_Hospital_ID']

payment_detail_mapping = dim_payment_detail.set_index(['Date_of_Payment', 'Program_Year', 'Payment_Publication_Date', 
                                                       'Form_of_Payment_or_Transfer_of_Value', 'Nature_of_Payment_or_Transfer_of_Value'])['dim_Payment_Detail_ID']

# Map IDs to the Fact Table
df_generalpaymentdata['dim_Covered_Recipient_ID'] = df_generalpaymentdata.set_index(['Covered_Recipient_First_Name', 'Covered_Recipient_Middle_Name',
                                               'Covered_Recipient_Last_Name', 'Covered_Recipient_Primary_Type_1',
                                               'Covered_Recipient_Specialty_1', 'Covered_Recipient_License_State_code1']).index.map(covered_recipient_mapping)

df_generalpaymentdata['dim_Teaching_Hospital_ID'] = df_generalpaymentdata.set_index(['Teaching_Hospital_ID', 'Teaching_Hospital_Name',
                                               'Recipient_Primary_Business_Street_Address_Line1', 'Recipient_City',
                                               'Recipient_State', 'Recipient_Zip_Code']).index.map(teaching_hospital_mapping)

df_generalpaymentdata['dim_Payment_Detail_ID'] = df_generalpaymentdata.set_index(['Date_of_Payment', 'Program_Year', 'Payment_Publication_Date', 
                                            'Form_of_Payment_or_Transfer_of_Value', 'Nature_of_Payment_or_Transfer_of_Value']).index.map(payment_detail_mapping)

# Fact General Payments Table
fact_general_payments = df_generalpaymentdata[['Total_Amount_of_Payment_USDollars', 
                 'Number_of_Payments_Included_in_Total_Amount', 
                 'Physician_Ownership_Indicator',
                 'dim_Covered_Recipient_ID',
                 'dim_Teaching_Hospital_ID',
                 'dim_Payment_Detail_ID']].copy()
fact_general_payments['Fact_id'] = range(1, len(fact_general_payments) + 1)

print(dim_covered_recipient.head())
print(dim_teaching_hospital.head())
print(dim_payment_detail.head())
print(fact_general_payments.head())

  Covered_Recipient_First_Name Covered_Recipient_Middle_Name  \
0                       JUSTIN                          <NA>
1                         RAVI                          <NA>
2                        JACOB                          <NA>
3                       JEREMY                       MICHAEL
4                         ERIC                             B

  Covered_Recipient_Last_Name Covered_Recipient_Primary_Type_1  \
0                    MITCHELL                   Medical Doctor
1                       PATEL                   Medical Doctor
2                    PFEIFFER             Doctor of Osteopathy
3                   PHILIPSEN     Doctor of Podiatric Medicine
4                       PIFEL                   Medical Doctor

                       Covered_Recipient_Specialty_1  \
0  Allopathic & Osteopathic Physicians|Orthopaedi...
1  Allopathic & Osteopathic Physicians|Orthopaedi...
2  Allopathic & Osteopathic Physicians|Orthopaedi...
3  Podiatric Medicine & Surgery Service Providers...
4  Allopathic & Osteopathic Physicians|Orthopaedi...

  Covered_Recipient_License_State_code1  dim_Covered_Recipient_ID
0                                    IA                         1
1                                    IL                         2
2                                    WI                         3
3                                    WI                         4
4                                    WI                         5
  Teaching_Hospital_ID Teaching_Hospital_Name  \
0                 <NA>                   <NA>
1                 <NA>                   <NA>
2                 <NA>                   <NA>
3                 <NA>                   <NA>
4                 <NA>                   <NA>

  Recipient_Primary_Business_Street_Address_Line1 Recipient_City  \
0                               3111 GUNDERSEN DR       ONALASKA
1                               420 N IL ROUTE 31   CRYSTAL LAKE
2                         8700 WATERTOWN PLANK RD      MILWAUKEE
3                   2835 N GRANDVIEW BLVD STE 300       PEWAUKEE
4                       3077 N MAYFAIR RD STE 100      WAUWATOSA

  Recipient_State Recipient_Zip_Code  dim_Teaching_Hospital_ID
0              WI         54650-8447                         1
1              IL         60012-3709                         2
2              WI         53226-3595                         3
3              WI         53072-5591                         4
4              WI         53222-4305                         5
  Date_of_Payment  Program_Year Payment_Publication_Date  \
0      2022-01-22          2022               2024-01-18
1      2022-09-06          2022               2024-01-18
2      2022-09-06          2022               2024-01-18
3      2022-09-26          2022               2024-01-18
4      2022-01-27          2022               2024-01-18

  Form_of_Payment_or_Transfer_of_Value Nature_of_Payment_or_Transfer_of_Value  \
0           In-kind items and services                      Food and Beverage
1           In-kind items and services                              Education
2           In-kind items and services                      Food and Beverage
3           In-kind items and services                      Food and Beverage
4           In-kind items and services                      Food and Beverage

   dim_Payment_Detail_ID
0                      1
1                      2
2                      3
3                      4
4                      5
   Total_Amount_of_Payment_USDollars  \
0                             124.14
1                            1200.00
2                               7.46
3                              12.79
4                              53.33

   Number_of_Payments_Included_in_Total_Amount Physician_Ownership_Indicator  \
0                                            1                            No
1                                            1                            No
2                                            1                            No
3                                            1                            No
4                                            1                            No

   dim_Covered_Recipient_ID  dim_Teaching_Hospital_ID  dim_Payment_Detail_ID  \
0                         1                         1                      1
1                         2                         2                      2
2                         2                         2                      3
3                         3                         3                      4
4                         4                         4                      5

   Fact_id
0        1
1        2
2        3
3        4
4        5

In [48]:
dim_covered_recipient.head()

,Covered_Recipient_First_Name,Covered_Recipient_Middle_Name,Covered_Recipient_Last_Name,Covered_Recipient_Primary_Type_1,Covered_Recipient_Specialty_1,Covered_Recipient_License_State_code1,dim_Covered_Recipient_ID
0,JUSTIN,<NA>,MITCHELL,Medical Doctor,Allopathic & Osteopathic Physicians|Orthopaedi...,IA,1
1,RAVI,<NA>,PATEL,Medical Doctor,Allopathic & Osteopathic Physicians|Orthopaedi...,IL,2
2,JACOB,<NA>,PFEIFFER,Doctor of Osteopathy,Allopathic & Osteopathic Physicians|Orthopaedi...,WI,3
3,JEREMY,MICHAEL,PHILIPSEN,Doctor of Podiatric Medicine,Podiatric Medicine & Surgery Service Providers...,WI,4
4,ERIC,B,PIFEL,Medical Doctor,Allopathic & Osteopathic Physicians|Orthopaedi...,WI,5

In [49]:
dim_teaching_hospital.head()

,Teaching_Hospital_ID,Teaching_Hospital_Name,Recipient_Primary_Business_Street_Address_Line1,Recipient_City,Recipient_State,Recipient_Zip_Code,dim_Teaching_Hospital_ID
0,<NA>,<NA>,3111 GUNDERSEN DR,ONALASKA,WI,54650-8447,1
1,<NA>,<NA>,420 N IL ROUTE 31,CRYSTAL LAKE,IL,60012-3709,2
2,<NA>,<NA>,8700 WATERTOWN PLANK RD,MILWAUKEE,WI,53226-3595,3
3,<NA>,<NA>,2835 N GRANDVIEW BLVD STE 300,PEWAUKEE,WI,53072-5591,4
4,<NA>,<NA>,3077 N MAYFAIR RD STE 100,WAUWATOSA,WI,53222-4305,5

In [50]:
dim_payment_detail.head()

,Date_of_Payment,Program_Year,Payment_Publication_Date,Form_of_Payment_or_Transfer_of_Value,Nature_of_Payment_or_Transfer_of_Value,dim_Payment_Detail_ID
0,2022-01-22,2022,2024-01-18,In-kind items and services,Food and Beverage,1
1,2022-09-06,2022,2024-01-18,In-kind items and services,Education,2
2,2022-09-06,2022,2024-01-18,In-kind items and services,Food and Beverage,3
3,2022-09-26,2022,2024-01-18,In-kind items and services,Food and Beverage,4
4,2022-01-27,2022,2024-01-18,In-kind items and services,Food and Beverage,5

In [51]:
fact_general_payments.head()

,Total_Amount_of_Payment_USDollars,Number_of_Payments_Included_in_Total_Amount,Physician_Ownership_Indicator,dim_Covered_Recipient_ID,dim_Teaching_Hospital_ID,dim_Payment_Detail_ID,Fact_id
0,124.14,1,No,1,1,1,1
1,1200.00,1,No,2,2,2,2
2,7.46,1,No,2,2,3,3
3,12.79,1,No,3,3,4,4
4,53.33,1,No,4,4,5,5